### ISSUE TITLE
Statistical significance of results on ContraPro

### ISSUE THREAD

**Issue by lorelupo** [ZurichNLP/ContraPro#5]
Dear authors, what kind of test would you suggest to evaluate the statistical significance of system results on ContraPro ?

**Comment by bricksdont** [comment]
Hi, I think that a t test would be the correct sigtest to use in this case, since the results are accuracy values.

More information on choosing an appropriate test:

https://www.aclweb.org/anthology/P18-1128.pdf
https://arxiv.org/pdf/1809.01448.pdf

**Comment by bricksdont** [comment]
@lorelupo I am assuming that this issue can be closed. If not, feel free to reopen / add a comment.

**Comment by lorelupo** [comment]
Yes, thank you for the answer !
